#!/bin/bash

##  Script to locally compile and install PG2PLplot 
##    for ifort, gfortran and g95
##  Install in ../usr/, clean afterwards
##  AF, 2010

make_gfortran=1
make_g95=0
make_ifort=0



if [ ${make_gfortran} -eq 1 ]; then
    echo -e "\n\nMake with gfortran:"
    make clean
    rm -f CMakeCache.txt
    FC=gfortran cmake -DSTOP_ON_WARNING=on -DCMAKE_INSTALL_PREFIX:PATH=/home/user/usr ..
    make install
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

if [ ${make_g95}  -eq 1 ]; then
    echo -e "\n\nMake with g95:"
    make clean
    rm -f CMakeCache.txt
    FC=g95 cmake -DSTOP_ON_WARNING=on -DCMAKE_INSTALL_PREFIX:PATH=/home/user/usr ..
    make install
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

if [ ${make_ifort}  -eq 1 ]; then
    echo -e "\n\nMake with ifort:"
    make clean
    rm -f CMakeCache.txt
    FC=ifort cmake -DSTOP_ON_WARNING=on -DCMAKE_INSTALL_PREFIX:PATH=/home/user/usr ..
    make install
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi


rm -rf ../usr/
rm -rf CMakeFiles/

